### PR TITLE
Support multiple comments options

### PR DESCRIPTION
**Pull request by theXappy**
pcapng specifications allow multiple occurrences of the 'comment' option within the 'Options' are of any bock

### CODE REVIEW

**Comment by theXappy** [comment]
Hey
The automatic pipeline fails because it tries to publish to the NuGet package and it fails (which it probably shouldn't even attempt)

**Comment by theXappy** [comment]
Hi @HakanL , can you take a look please?

**Review by HakanL — APPROVED** [review]

**Comment by HakanL** [comment]
Sorry @theXappy about the delay, for some reason I never received notifications for this repo. I'll merge, thanks for your contribution!

**Comment by theXappy** [comment]
That's ok, thank you for maintaining it :)
Does it help if I do the "mention" ( @HakanL ) thing? Do you get notifications for those?

**Comment by HakanL** [comment]
Yes, that helps, that's how I saw this PR, but I don't get why the repo that I own doesn't notify me. I've tried some settings now as well, maybe that will help.

**Pull request merged**
